# Cluster Settings
cluster:
  name: elasticsearch_medcl

# Path Settings
#path:
#  conf: /path/to/conf
#  data: /path/to/data
#  work: /path/to/work
#  logs: /path/to/logs

# Gateway Settings
#gateway:
#  recover_after_nodes: 1
#  recover_after_time: 5m
#  expected_nodes: 2


# Force all memory to be locked, forcing JVM to never swap
#  (make sure to set MIN and MAX mem to the same value)
#bootstrap:
#  mlockall: true

# Unicast Discovery (disable multicast)
#discovery:
#  zen:
#    ping.multicast.enabled: false
#    ping.unicast.hosts: ["host1", "host2"]

#for ik, use type: org.elasticsearch.index.analysis.IkAnalyzerProvider  or name: ik
#index:
#  analysis:
#    analyzer:
#      ik12:
#          alias: [news_analyzer, news_analyzer_ik]
#          type: custom
#          filter: [standard, lowercase, stop, word_delimiter]
#          tokenizer: standard

#        tokenizer: myTokenizer1
#        filter: [myTokenFilter1, myTokenFilter2]
#        char_filter: [my_html]
#    tokenizer:
#      myTokenizer1:
#        type: standard
#        max_token_length: 900
#    filter:
#      myTokenFilter1:
#        type: stop
#        stopwords: [stop1, stop2, stop3, stop4]
#      myTokenFilter2:
#        type: length
#        min: 0
#        max: 2000
#    char_filter:
#      my_html:
#        type: html_strip
#        escaped_tags: [xxx, yyy]
#        read_ahead: 1024
