# Cluster Settings
cluster:
  name: elasticsearch_medcl

thrift:
  port: 9500
  protocol: 'binary'

# Path Settings
#path:
#  conf: /path/to/conf
#  data: /path/to/data
#  work: /path/to/work
#  logs: /path/to/logs

# Gateway Settings
#gateway:
#  recover_after_nodes: 1
#  recover_after_time: 5m
#  expected_nodes: 2


# Force all memory to be locked, forcing JVM to never swap
#  (make sure to set MIN and MAX mem to the same value)
#bootstrap:
#  mlockall: true

# Unicast Discovery (disable multicast)
#discovery:
#  zen:
#    ping.multicast.enabled: false
#    ping.unicast.hosts: ["host1", "host2"]

index:
  analysis:
    analyzer:

      ik:
          alias: [news_analyzer, news_analyzer_ik,ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider

      my_analyzer:
          alias: [my_analyzer1]
          type: custom
          filter: [standard, lowercase, stop, word_delimiter]
          tokenizer: standard

      my_analyzer2:
          alias: [my_analyzer3]
          type: custom
          filter: [lowercase, stop, word_delimiter]
          tokenizer: whitespace

      my_analyzer4:
          type: custom
          filter: [standard, lowercase, stop, word_delimiter]
          tokenizer: myTokenizer1
          filter: [myTokenFilter1, myTokenFilter2]
          char_filter: [my_html]

    tokenizer:
      myTokenizer1:
        type: whitespace
        max_token_length: 900
    filter:
      myTokenFilter1:
        type: stop
        #stopwords: [xxx, stop2, stop3, stop4]
      myTokenFilter2:
        type: length
        min: 0
        max: 2000
    char_filter:
      my_html:
        type: html_strip
        #escaped_tags: [xxx, yyy]  #if not explicit set will remove all tags
        read_ahead: 1024
